name: Docker Image CI

env:
  IMAGE_NAME: tno/ssi-gateway-acapy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}:${{ github.sha }}
    - uses: Azure/container-scan@v0
      with:
        image-name: ${{env.IMAGE_NAME}}:${{ github.sha }}
